#! /usr/bin/python

# This file should be a executable which will be called by the server script(PHP for now)
import sys, os, random

sys.path.append("/home/luanjunyi/yhhd/py")
from crawler.tuchong.db import dbAgent



def get_next_image_for_user(uid):
    agent = dbAgent(db_name="picful", db_user="taras", db_pass="admin123", sscursor=True)
    all_pic = agent.get_all_pic()
    return random.choice(all_pic)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print "expecting one command line argument"
    else:
        user_id = sys.argv[1]
        # user_id is 100% user input and you should process it to prevent SQL injection
        next_pic = get_next_image_for_user(user_id)
        print next_pic['id'], next_pic['filepath']

    
