#! /usr/bin/python
# -*- coding: utf-8 -*-
import os, sys, traceback
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../../') # Paracode root
from taras import taras
from util.log import _logger


def usage():
    print 'usage: clean_following -u(user=tarse) -d(db=taras) -p(passwd=admin123) -h(host=localhost) -e(email="")'
    sys.exit(0)

def main(argv):
    from getopt import getopt
    try:
        opts, args = getopt(sys.argv[1:], 'u:d:p:h:e:', ['user=', 'db=', 'passwd=', 'host=', 'email='])
    except Exception, err:
        print "getopt error:%s" % err
        usage()
        sys.exit(2)

    dbuser = 'taras'
    db = 'taras'
    passwd = 'admin123'
    host =  'localhost'
    email = None # None means processing all users
    for opt, arg in opts:
        if opt in ('-u', '--user'):
            dbuser = arg
        if opt in ('-d', '--db'):
            db = arg
        if opt in ('-p', '--passwd'):
            passwd = arg
        if opt in ('-h', '--host'):
            host = arg
        if opt in ('-e', '--email'):
            email = arg


    daemon = taras.WeiboDaemon(dbname=db, dbuser = dbuser, dbpass = passwd, noselenium=True, mysql_host=host)
    try:
        daemon.force_stop_follow_stubborn(email)
    except Exception, err:
        _logger.error('clean_following failed: %s, %s' % (err, traceback.format_exc()))
    finally:
        daemon.shutdown()

if __name__ == "__main__":
    main(sys.argv[1:])
