#!/bin/bash
set -u
set -e

vnc4server
export DISPLAY=:1.0
ohup java -jar /home/luanjunyi/yhhd/py/third_party/selenium-server-standalone-2.0.0.jar &nohup java -jar /home/luanjunyi/yhhd/py/third_party/selenium-server-standalone-2.0.0.jar &
