#! /usr/bin/python
# -*- coding: utf-8 -*-
import sys, traceback, os
import MySQLdb
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/../../') # Paracode root
from taras import taras
from util.log import _logger

def usage():
    print 'usage: update_statistic_race -u[USER=tarse] -d[DB=taras] -p[PASSWD=admin123]'
    sys.exit(0)

def main(argv):
    from getopt import getopt
    try:
        opts, args = getopt(sys.argv[1:], 'u:d:p:', ['user=', 'db=', 'passwd='])
    except Exception, err:
        print "getopt error:%s" % err
        usage()
        sys.exit(2)

    dbuser = 'taras-race'
    db = 'taras_race'
    passwd = 'mhxzkhl'
    for opt, arg in opts:
        if opt in ('-u', '--user'):
            dbuser = arg
        if opt in ('-d', '--db'):
            db = arg
        if opt in ('-p', '--passwd'):
            passwd = arg

    daemon = taras.WeiboDaemon(dbname=db, dbuser = dbuser, dbpass = passwd)
    agent = taras.SQLAgent(dbname=db, uname=dbuser, passwd=passwd)
    for user in agent.get_all_account_in_race():
        try:
            api = daemon.get_api_on_the_fly(user.uname, user.passwd)
            stat = daemon.get_user_statistic(user, api)
            agent.update_db_statistic(stat)
        except Exception, err:
            _logger.error('update_statistic failed: %s, %s' % (err, traceback.format_exc()))


    daemon.shutdown()

if __name__ == "__main__":
    main(sys.argv[1:])
